apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-console-config
  namespace: {{ .Values.installation.namespace }}
data:
  polaris-console.yaml: |-
    logger:
      RotateOutputPath: log/polaris-console.log
      RotationMaxSize: 500
      RotationMaxAge: 30
      RotationMaxBackups: 100
      level: info
    webServer:
      mode: "release"
      listenIP: "0.0.0.0"
      listenPort: {{ .Values.service.webPort }}
      namingV1URL: "/naming/v1"
      namingV2URL: "/naming/v2"
      authURL: "/core/v1"
      requestURL: "/naming/v1"
      configURL: "/config/v1"
      monitorURL: "/api/v1"
      webPath: "web/dist/"
    polarisServer:
      address: "127.0.0.1:{{ .Values.service.httpPort }}"
      polarisToken: "polaris@12345678"
    monitorServer:
      address: "polaris-prometheus:9090"
    oaAuthority:
      enableOAAuth: false
    hrData:
      enableHrData: false
